graph TD
    Environment --> Template
    Blueprint --> Template
    Input_1 --> Template
    Input_2 --> Template
    Template --> Deployment
    Deployment --> State
    Deployment --> Output_1
    Deployment --> Output_2
    Deployment --> Log_1
    Deployment --> Log_2
